import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({ //stylesheet for Sano
  container: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    padding: 26,
  },
  title: {
    marginTop: 135,
    color: '#0F1A1D',
    fontSize: 64,
    fontWeight: 600,
    width: '100%',
    textAlign: 'left',
    marginBottom: -10,
  },
  slogan: {
    color: '#0F1A1D',
    fontSize: 20,
    fontWeight: 600,
    width: '100%',
    textAlign: 'right',
    paddingRight: 7,
  },
  box: {
    marginTop: 50,
    width: '100%',
    minHeight: '33%',
    maxHeight: '40%',
    backgroundColor: '#488286',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 0,
    marginBottom: 15,
  },
  signInHeadingContainer: {
    width: '100%',
    alignItems: 'flex-start',
    paddingLeft: 33,
  },
  signInHeading: {
    fontSize: 32,
    fontWeight: 'bold',
    marginBottom: 27,
    color: '#FFFFFF',
  },
  heading: {
    marginTop: 90,
    fontSize: 32,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#2A3A3E',
    width: '100%',
    textAlign: 'left',
    paddingLeft: 13,
  },
  input: {
    width: '80%',
    height: '15%',
    paddingLeft: 15,
    paddingRight: 15,
    paddingTop: 10,
    paddingBottom: 10,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 20,
    marginBottom: 18,
    backgroundColor: '#F9F9F9',
    boxShadow: '0 4px 4px 0 rgba(0, 0, 0, 0.25)',
    fontSize: 12.5,
  },
  errorText: {
    color: 'red',
    fontSize: 14,
  },
  enabledLoginButton: {
    width: '80%',
    backgroundColor: '#4DBBBB', // Enabled color
    padding: 15,
    borderRadius: 20,
    alignItems: 'center',
    boxShadow: '0 5px 5px 0 rgba(0, 0, 0, 0.25)',
    marginTop: 15,
  },
  disabledLoginButton: {
    width: '80%',
    backgroundColor: '#77888C', // Disabled color
    padding: 15,
    borderRadius: 20,
    alignItems: 'center',
    marginTop: 13,
  },
  loginButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  imageButton: {
    width: '100%',
    padding: 0,
    marginTop: 20,
    borderRadius: 30,
    overflow: 'hidden',
    border: '1px solid rgba(255, 255, 255, 0.10)',
    marginBottom: 350,
  },
  imageBackground: {
    width: '100%',
    height: 190,
    justifyContent: 'flex-end', 
    alignItems: 'flex-start',
    overflow: 'hidden',
  },
  imageBackgroundText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 500,
    paddingLeft: 27,
    paddingBottom: 20,
  },
  normalColor: {
    fontSize: 18,
    fontStyle: 'normal',
    color: '#2A3A3E',
    lineHeight: 25,
    paddingLeft: 14,
    paddingRight: 14,
  },
  normalWhite: {
    fontSize: 18,
    fontStyle: 'normal',
    color: '#FFFFFF',
    lineHeight: 25,
    fontWeight: 600,
    paddingLeft: 14,
    paddingRight: 14,
  },
  symptoms: {
    marginTop: 25,
    marginLeft: -3,
    width: 338,
    height: 432,
  },
  bold: {
    color: '#2A3A3E',
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 10,
    marginBottom: 10,
    width: '100%',
    textAlign: 'left',
    paddingLeft: 14,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginTop: 27,
  },
  backButton: {
    backgroundColor: '#488286',
    padding: 10,
    marginLeft: 6,
    borderRadius: 20,
    boxShadow: '0 4px 4px 0 rgba(0, 0, 0, 0.25)',
  },
  continueButton: {
    backgroundColor: '#4DBBBB',
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 10,
    paddingBottom: 10,
    marginRight: 6,
    borderRadius: 20,
    boxShadow: '0 4px 4px 0 rgba(0, 0, 0, 0.25)',
  }
});

export default styles;